name: formz_dev
description: Dev utils for the formz library

publish_to: 'none'

version: '1.0.0'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: '>=1.0.4'

  source_gen: ^1.0.0
  code_builder: ^4.1.0
  analyzer: ^4.7.0
  dart_style: ^2.2.1

  flutter_bloc: ^8.0.1

  formz:
    path: ../formz

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.3