builders:
  tupleGeneratorBuilder:
    import: "package:formz/gen/tuple_generator.dart"
    builder_factories: ["tupleGeneratorBuilder"]
    build_extensions: {".dart": [".tuple.dart"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      formz|tupleGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/formz.dart