builders:
  tupleGeneratorBuilder:
    import: "package:formz/gen/tuple_generator.dart"
    builder_factories: ["tupleGeneratorBuilder"]
    build_extensions: {".dart": [".tuple.dart"]}
    auto_apply: root_package
    build_to: source
  mergeGeneratorBuilder:
    import: "package:formz/gen/merge_generator.dart"
    builder_factories: ["mergeGeneratorBuilder"]
    build_extensions: {".dart": [".merge.dart"]}
    auto_apply: root_package
    build_to: source
  consumableFuncGeneratorBuilder:
    import: "package:formz/gen/consumable_func_generator.dart"
    builder_factories: ["consumableFuncGeneratorBuilder"]
    build_extensions: {".dart": [".con.dart"]}
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      formz|tupleGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/formz.dart
      formz|mergeGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/formz.dart
      formz|consumableFuncGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/formz.dart