name: formz
description: Generalizes form validation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: '1.0.2'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # for state management
  flutter_bloc: '>=7.0.0 <8.0.0'
  equatable: '>=2.0.3 <3.0.0'
  freezed_annotation: '>=0.14.2 <0.15.0'

  # stream utils
  rxdart: '>=0.27.1 <0.28.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: '>=2.0.5 <3.0.0'

  freezed: '>=0.14.2 <0.15.0'

  source_gen: '>=1.1.0 <1.2.0'
  code_builder: '>=4.0.0 <4.2.0'

  bloc_test: '>=8.1.0 <9.0.0'
  mockito: '>=5.0.10 <6.0.0'

  formz_test:
    path: ../app-formz-test
#    git: ssh://git@github.com/TinDan-Dev/app-formz-test.git

