name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY}}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      - name: Get Dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format -l 120 --output=none --set-exit-if-changed .
      
      - name: Code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Analyze
        run: flutter analyze

      - name: Tests
        run: flutter test
