name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY}}
      #     name: id_rsa
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'

      - name: Get dependencies
        working-directory: ./formz
        run: flutter pub get

      - name: Verify formatting
        working-directory: ./formz
        run: dart format -l 120 --output=none --set-exit-if-changed .
      
      - name: Code generation
        working-directory: ./formz
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Analyze
        working-directory: ./formz
        run: flutter analyze

      - name: Tests 
        working-directory: ./formz
        run: flutter test

      - name: Get dev dependencies
        working-directory: ./formz_dev
        run: flutter pub get

      - name: Verify dev formatting
        working-directory: ./formz_dev
        run: dart format -l 120 --output=none --set-exit-if-changed .

      - name: Analyze dev
        working-directory: ./formz_dev
        run: flutter analyze
